version: '3'

services:
  roscore:
    image: osrf/ros:noetic-desktop-full
    network_mode: host
    command: stdbuf -o L roscore

  dynamxiel_controllers:
    build:
      context: .
      dockerfile: dockerfile
    image: dynamixel-workbench/noetic:latest
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
      # - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - Dynamixel_ROS:/Dynamixel_ROS
      - /dev/shm:/dev/shm 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    depends_on:
      - roscore
    command: roslaunch dynamixel_workbench_controllers dynamixel_controllers.launch --wait

  dynamxiel_operator:
    build:
      context: .
      dockerfile: dockerfile
    image: dynamixel-workbench/noetic:latest
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
      # - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - Dynamixel_ROS:/Dynamixel_ROS
      - /dev/shm:/dev/shm 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    depends_on:
      - roscore
    command: roslaunch dynamixel_workbench_operators joint_operator.launch --wait

  volumes:
  dynamxixel_as:
   driver: local
   driver_opts:
    o: bind
    type: none
    device: ../Dynamixel_ROS